[package]
name = "terrain-road-generator"
version = "0.2.0"
edition = "2021"

[dependencies]
image = "0.24"
indicatif = "0.17"
nalgebra = "0.33"
rand = "0.8"
rand_pcg = "0.3"
rayon = "1.7"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"